name: M-Studios
favicon: null
layout_spectrum: 0
typography_spectrum: 0.44103
title: M - Studios
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#393939'
    - '#dc0000'
    - '#9b9b9b'
    - '#ef8283'
  brandStrength: 0.5625
  lightness: 1
  saturation: 0.625
  rhythmicContrast: 1
purpose: []
