name: M-Studios
favicon: null
layout_spectrum: 0.6338
typography_spectrum: 0.16048
title: M - Studios
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f36523'
    - '#265368'
    - '#feb63d'
    - '#668694'
  brandStrength: 0.5625
  lightness: 0.375
  saturation: 0.1875
  rhythmicContrast: 0
purpose: []
